### ISSUE TITLE
Undocumented/internal specifications

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch-specification#1010]
## 🚀 Feature Proposal

Add "internal" to the [stability](https://github.com/elastic/elasticsearch-specification/blob/main/docs/modeling-guide.md#stability) tag or add a new tag to indicate APIs or properties that should not be externalized.

## Motivation

There are some APIs for which we have specifications, but which we intentionally do not document. I think the intention is that those APIs are used internally (e.g. for Kibana) but might never be externalized. I think it might be something that should affect client code generation too.

## Example

Here are some ML APIs that are currently intentionally undocumented:

* https://github.com/elastic/elasticsearch-specification/blob/main/specification/ml/validate/MlValidateJobRequest.ts
* https://github.com/elastic/elasticsearch-specification/blob/main/specification/ml/validate_detector/MlValidateDetectorRequest.ts

Per @jrodewig Elasticsearch has some intentionally undocumented REST APIs too (https://github.com/elastic/elasticsearch/issues/76201). However, we currently don’t produce specs for them. It’d be great if we could provide consistent advice on how to handle this type of situation.

**Comment by delvedor** [comment]
Hello! This is already supported via the `@visibility` tag :)
https://github.com/elastic/elasticsearch-specification/blob/8dbf19a0b307b0e03b6cd9955aebf7941104b04e/compiler/model/metamodel.ts#L339-L343
It looks like we forgot to document it, I'll send a pr for it :)

**Comment by lcawl** [comment]
Thanks!
