### ISSUE TITLE
Incorrect Response content-type for nodes.hot_threads

### ISSUE THREAD

**Issue by philkra** [elastic/elasticsearch-specification#1206]
The response of `nodes.hot_threads`: 

```
make validate stack-version=8.0.0-SNAPSHOT type=response api=nodes.hot_threads
```

Text instead of JSON is returned. Can you confirm that the correct header is emitted?

**Comment by delvedor** [comment]
According to the API the response is always string: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-hot-threads.html
I tried to send a request with `?format=json` but I'm still getting back a text/plain.

Not sure why we have a structured definition, I suspect a nestism, maybe @stevejgordon knows more?

**Comment by dadoonet** [comment]
Apparently this is causing an issue with the Java client: https://github.com/elastic/elasticsearch-java/issues/865
