### ISSUE TITLE
Add health and status properties to the Indices Stats API spec

### ISSUE THREAD

**Issue by yuliacech** [elastic/elasticsearch-specification#1253]
## 🐛 Wrong type
The Indices Stats API has [been updated](https://github.com/elastic/elasticsearch/pull/81954) to include index `health` and `status`. It would be great to add those properties to the [IndicesStats spec](https://github.com/elastic/elasticsearch-specification/blob/main/specification/indices/stats/types.ts).

<img width="806" alt="Screenshot 2022-01-12 at 17 25 53" src="https://user-images.githubusercontent.com/6585477/149181107-3acb20a2-49ed-41d0-b4ee-bfa077255019.png">

## Definition

```diff
export class IndicesStats {
   primaries?: IndexStats
   shards?: Dictionary<string, ShardStats[]>
   total?: IndexStats
   uuid?: Uuid
+ health?: string // "green", "yellow, "red"
+ status?: string // "open", "close"
}
```

**Comment by philkra** [comment]
Thank you @yuliacech - I opened https://github.com/elastic/elasticsearch-specification/pull/1254 to add the fields.
