### ISSUE TITLE
update-model-info is not enabled in the 8.0 branch

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch-specification#1308]
The 8.0 branch is not selected in https://github.com/elastic/elasticsearch-specification/blob/8.0/.github/workflows/update-model-info.yml, causing git hash in `schema.json` to point to the `main` branch in backports.

While the fix is easy, I'm wondering if that feature is worth doubling the number of commits in the spec repo just to replace running `git rev-parse --short HEAD` to get the same information.

Are there uses for the `schema.json`'s hash in places where the repo isn't available to run `git rev-parse --short HEAD`?

**Comment by delvedor** [comment]
Closed by https://github.com/elastic/elasticsearch-specification/pull/1385.
