### ISSUE TITLE
Add `features` parameter to Get Index API

### ISSUE THREAD

**Issue by yuliacech** [elastic/elasticsearch-specification#1382]
## 🐛 Wrong type
The Get Index API has [been updated](https://github.com/elastic/elasticsearch/pull/83083) to expose the parameter `features` to avoid computing some of the index properties when requesting the API. It would be great to add this option to the `IndicesGetRequest` [spec](https://github.com/elastic/elasticsearch-specification/blob/main/specification/indices/get/IndicesGetRequest.ts). The value can be one of `aliases`, `mappings` or `settings` or a combination of those. The default is `aliases,mappings,settings`.

**Comment by philkra** [comment]
@yuliacech thank you very much for reporting the missing property, I opened the PR https://github.com/elastic/elasticsearch-specification/pull/1562 to address this change. The release of the client will contain the new property.
