### ISSUE TITLE
Specification change for `specLocation` & `meta` property

### ISSUE THREAD

**Issue by philkra** [elastic/elasticsearch-specification#1484]
The current format of `specLocation` is verbose:

```
"specLocation": {
     "endLine": 632,
     "path": "_types/aggregations/Aggregate.ts",
     "startLine": 628
},
```

The shape should be changed to a more lenient format as shown below:

```
"meta": {
     "specLocation": "_types/aggregations/Aggregate.ts:628:632"
}
``` 

Furthermore, I propose to anchor this information under a new property `meta` that will be build out over time.

**Comment by swallez** [comment]
If we're to use a more compact form, let's use the GitHub permalink syntax, i.e. `_types/aggregations/Aggregate.ts#L628-L632` which, along being directly usable to generate links, is less ambiguous about what these numbers mean with the `L` prefix.

Rationale: the `file:x:y` form is commonly used to indicate a position, `x` being the line and `y` being the column or character position in the line).

**Comment by philkra** [comment]
I prefer the format you suggest: `_types/aggregations/Aggregate.ts#L628-L632` lets use that one. So you are in agreement for this change?

**Comment by delvedor** [comment]
Big +1 for this change, not entirely sure we need too wrap it in a `meta` object It might be overkill for now. Anyhow, I'm fine in either case.

**Comment by philkra** [comment]
we can ditch the `meta` property for now, I do recommend introducing it if we add another meta'esque value into the mix.

**Comment by delvedor** [comment]
I've opened https://github.com/elastic/elasticsearch-specification/pull/1485, the new format reduces massively the verbosity of the json output.

**Comment by swallez** [comment]
> So you are in agreement for this change?

`schema.json` is meant for machines so reducing verbosity isn't a big concern, although it will help when we occasionally have to look at it. It will require an update to the Java code generator but it's not a big issue.

I'm not sure what other information may go in a `meta` field that could not be a regular model property. So we can remove it, which will further increase terseness.

**Comment by philkra** [comment]
So we're in favour of this change and can proceed? 👍

**Comment by swallez** [comment]
Yes, go for it! As a summary, it's now simply:

```
"specLocation": "_types/aggregations/Aggregate.ts#L628-L632"
```

**Comment by philkra** [comment]
Yes, that the one to use. @delvedor can you confirm you used the format from this comment: https://github.com/elastic/elasticsearch-specification/issues/1484#issuecomment-1042770456 and then proceed with the open PR https://github.com/elastic/elasticsearch-specification/pull/1485 ?

**Comment by delvedor** [comment]
Yes! :)
https://github.com/elastic/elasticsearch-specification/pull/1485/files#diff-310132f25213896a7f77c09b2922bc536aeb142fca56aa6c920d2cf8cb55044eR1218
