### ISSUE TITLE
Missing index mapping settings

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch-specification#1499]
Reported by @javanna for the 7.17 Java client: the `index.mapping.total_fields.limit` index setting is missing.

Digging further, it seems most (it not all) of the [index mapping settings](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-settings-limit.html) are missing from the spec.

We should also double check all the "[settings in other index modules](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules.html#_settings_in_other_index_modules)" section of index settings.

Discussing this issue with @javanna, a few things came up:
* the full list of index mapping settings is [defined statically in the ES code base](https://github.com/elastic/elasticsearch/blob/0478e5a4b5e4bd4fba355a02763f271c55839380/server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java#L50). An exhaustive list of settings and they type (or even the `IndexSettings` TS type) could be generated from that code. This can be a build-time thing and doesn't have to be a new ES API.
* the `IndexSettings` type need an "escape hatch" so that users can add settings that would be missing from the API spec. Having `IndexSettings implements AdditionalProperties<string, UserDefinedValue>` should be enough.

**Comment by philkra** [comment]
Opened the PR to add the missing props: #1500
