### ISSUE TITLE
[8.2.0] Add response type for `ml.getMemoryStats`

### ISSUE THREAD

**Issue by darnautov** [elastic/elasticsearch-specification#1538]
## 🐛 Missing type

https://github.com/elastic/elasticsearch/pull/83802 (`8.2.0`) introduced a new API endpoint for ML memory stats. `getMemoryStats` method is already provided by the ES client but the return type is missing.

**Comment by philkra** [comment]
@darnautov , thank you for reporting the missing API. I opened the PR https://github.com/elastic/elasticsearch-specification/issues/1538 to add it. Once merged, the subsequent client release will contain the API.
