### ISSUE TITLE
significant terms aggregation missing regex include method

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch-specification#1553]
Found in https://github.com/elastic/elasticsearch-java/issues/85

The definition of `SignificantTermsAggregation.include: string|string[]` does not represent the usual array leniency. Both variants have a specific meaning, resp. regexp and term list.

It should be typed as `TermsInclude`.

**Comment by philkra** [comment]
Addressed via https://github.com/elastic/elasticsearch-specification/pull/1556 - this issue will be auto closed on merged
