### ISSUE TITLE
Support “openapi / json schema” as compilation target 

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch-specification#1659]
## 🚀 Feature Proposal

Aside “java client” and “typescript client”, it would be great to add a “compilation target”: openapi & json schema. 

## Motivation/Examples

This would be very useful for several use cases:
- use json schema to have completion and validation for an index template json file, using an IDE like VSCODE.
- use openapi3 schema to expose elasticsearch api in a service gateway with schema validation. 
- another use would be in a IDE extension, that use openapi/json schema to provide completion for queries
- It could be used also in Kibana Dev tools for precise and complete completion on every api.

**Comment by swallez** [comment]
It has been done quite some time ago. Find the OpenAPI schema in https://github.com/elastic/elasticsearch-specification/tree/main/output/openapi

Sorry for forgetting about this issue.
