### ISSUE TITLE
SLM Java Client Missing Required Policy Config Element (indices)

### ISSUE THREAD

**Issue by jaijhala** [elastic/elasticsearch-specification#1917]
It seems that SLM Java Client is missing Required Policy Config Element (indices).

Example: 
Use the GUI interface to set up the SLM policy and take a snapshot of everything. 

When a user tries to use it in an application to validate that the SLM is running properly, it's not able to get the lifecycle because they don't have an `indices` element on the SLM policy configuration.
The documentation seems to say that the indices element on the policy config is optional, **but the Java api requires it.**
Tried using the `ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(true);` to try and get around this, but then got a null pointer exception.

**Comment by swallez** [comment]
@jaijhala This has been fixed in #1951 and will be part of the Java client 8.5.0 and 7.17.7
