### ISSUE TITLE
GeoHexGrid aggregation missing from Aggregate.ts

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch-specification#1974]
This aggregation has been added in https://github.com/elastic/elasticsearch-specification/pull/1579 but stil is missing from https://github.com/elastic/elasticsearch-specification/blob/main/specification/_types/aggregations/Aggregate.ts

**Comment by sethmlarson** [comment]
Completed in https://github.com/elastic/elasticsearch-specification/pull/1975
