### ISSUE TITLE
Missing 'similarity' field in knn search request

### ISSUE THREAD

**Issue by adrian-arapiles** [elastic/elasticsearch-specification#2149]
From 8.8 version, elasticsearch has field 'similarity' for search in knn field.
Right now, the api doesn't support this field and fail.
## 🐛 Missing type

https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#_search_knn_with_expected_similarity
Unknown field 'similarity' (JSON path: similarity) (line no=2, column no=15, offset=16)
## Definition

If possible provide a basic definition that we can use as base.
You can see [here](https://github.com/elastic/elasticsearch-specification/blob/master/docs/add-new-api.md) how to create a basic definition for any API.

**Comment by adrian-arapiles** [comment]
I tried to push a branch with the change, but I haven't permissions.

**Comment by AlmostFamiliar** [comment]
https://github.com/elastic/elasticsearch-java/issues/411 Related. 

I also tried to open a PR with the fix, but same issue.

**Comment by ezimuel** [comment]
@adrian-arapiles did you fork the project and send a PR from a branch in your fork? You cannot create a branch in the original repository. /cc @AlmostFamiliar

**Comment by JoshMock** [comment]
#2261 is merged and backported to 8.8, 8.9 and 8.10, so this should be fixed in the next patch release for each of those, or 8.11.0 when it releases.
