### ISSUE TITLE
 Add sub_searches to the search endpoint

### ISSUE THREAD

**Issue by ezimuel** [elastic/elasticsearch-specification#2162]
The `sub_searches` field has been [recently added](https://github.com/elastic/elasticsearch/pull/96224) in the search API for Elasticsearch.

## 🐛 Missing type

The `sub_searches` parameter in the body for the search API.

## Definition

A new top-level element to the search endpoint called `sub_searches`. This top-level element allows for a list of additional searches where each "sub search" will have a query executed separately as part of ranking and later combined into a final single set of documents based on the ranking algorithm.

The sub_searches element is used instead of query (and they may not be used together) to allow a search using ranking to execute multiple queries.

For more information have a look at [this PR](https://github.com/elastic/elasticsearch/pull/96224).

cc @jdconrad

**Comment by serenachou** [comment]
Note - this is deprioritized based on genai offsite discussions on the changes needed for RRF. Reference; https://elastic.slack.com/archives/C05DZGV6WS2/p1690463067159829
