### ISSUE TITLE
Add support for ignore_missing_conponent_templates in put_index_template

### ISSUE THREAD

**Issue by honzakral** [elastic/elasticsearch-specification#2254]
This parameter is not supported and there is no workaround.

This is another result of the undocumented removal of the body parameter (see elastic/elasticsearch-py#2181) which is making the client unusable for some scenarios.

**Comment by pquentin** [comment]
> This parameter is not supported and there is no workaround.

This issue was transferred from elasticsearch-py, and indeed with the current Python client, one needs to perform a raw request when even a single key is missing from the specification.

**Comment by pquentin** [comment]
This was fixed by @l-trotta in #2488. Closing, thanks!
