### ISSUE TITLE
Empty interfaces should not exists

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch-specification#226]
Due to how the TypeScript type system works, if you define an empty interface, then every object will be accepted.

Eg:

```ts
import { expectAssignable, expectType } from 'tsd'

interface Foo {}

expectAssignable<Foo>({ hello: 'world' })
expectType<Foo>({ hello: 'world' })
```

The test above will pass.

The only way to make the test above fail is to use the TypeScript `never` type:
```ts
import { expectAssignable, expectType } from 'tsd'

interface Foo {
  [k: string]: never
}

expectAssignable<Foo>({ hello: 'world' })
expectType<Foo>({ hello: 'world' })
```

It's very hard to determine the impact of this change in our test, but given that is a fairly simple step to add in the TypeScript generator, it's easier to just do it and see what happens.

**Comment by swallez** [comment]
I understand this only impacts the TS generator used for flight-recorder? Or do we want to remove empty interfaces entirely from the API spec?

**Comment by delvedor** [comment]
It impacts only the typescript generator, but it will help us detect empty definitions in the spec.

**Comment by delvedor** [comment]
Closed in https://github.com/elastic/elasticsearch-specification/pull/600.
