### ISSUE TITLE
SecurityRealm type in SecurityPutRoleMappingRequest results in a parsing error.

### ISSUE THREAD

**Issue by kristianthorsen** [elastic/elasticsearch-specification#2344]
## 🐛 Bug Report

The SecurityPutRoleMappingRequest type expects to specify a SecurityRealm in a SecurityFieldRule of a SecurityRule as:

```typescript
  {
  field: {
    realm: {
      name: "RealmName"
    }
  }
}
```

However doing this results in the following parsing error:

Error: parsing_exception
	Caused by:
		x_content_parse_exception: [1:77] [role-mapping] failed to parse field [rules]
	Root causes:
		parsing_exception: [1:77] [role-mapping] failed to parse field [rules]

I have played a bit around with it and got the desired behaviour by changing the input to:

```typescript
  {
  field: {
    "realm.name": "RealmName"
  }
}
```

It seems that the type SecurityRealm type should either be changed to use "realm.name" or handle the behaviour before forwarding the body to the api.

## To Reproduce

Attempt to call the elasticsearch client with .security.putRoleMapping() containing the input described above

## Expected behavior

I expected the elasticsearch client to map the specified type to an accepted api request before forwarding the apicall.

## Your Environment

- *node version*: ">=18.0.0"
- `@elastic/elasticsearch` *version*: "^8.7.0"
- *os*: Linux

**Comment by JoshMock** [comment]
@kristianthorsen I've moved this issue to the specification repo, where we manage the spec used to generate API functions for all Elasticsearch clients.

Started taking a look, but this one is a bit hard to trace back for me. Hope to get to it more seriously soon.

**Comment by kristianthorsen** [comment]
> @kristianthorsen I've moved this issue to the specification repo, where we manage the spec used to generate API functions for all Elasticsearch clients.
> 
> 
> 
> Started taking a look, but this one is a bit hard to trace back for me. Hope to get to it more seriously soon.

Hi @JoshMock

Thank you very much.

Let me know if you want me to have a look at it.

**Comment by JoshMock** [comment]
@pquentin since you just merged https://github.com/elastic/elasticsearch-specification/pull/2357 and are familiar with `SecurityPutRoleMappingRequest`, I'm curious if anything about this issue jumps out at you? If not I'll take a look when I have time.

**Comment by pquentin** [comment]
Thanks @JoshMock, I confirmed the issue and opened #2362 to fix it.
