### ISSUE TITLE
Generate OAS for APIs that have stack availability

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch-specification#2399]
## 🚀 Feature Proposal

In addition to the https://github.com/elastic/elasticsearch-specification/blob/main/output/openapi/elasticsearch-serverless-openapi.json output file, we need one that reflects the APIs that have `availability` set to `stack`. 

In the past, that larger OAS file was generated and stored in a separate internal repo, but I don't know how up-to-date that one is.

## Motivation

We'll need the full set of public APIs in OAS format in order to generate API documentation.

## Example

N/A

**Comment by lcawl** [comment]
Fixed by https://github.com/elastic/elasticsearch-specification/pull/2608 ?

**Comment by l-trotta** [comment]
yes!
