### ISSUE TITLE
Missing analyzer: ICU

### ISSUE THREAD

**Issue by JoshMock** [elastic/elasticsearch-specification#2439]
The [ICU analysis](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html) plugin is currently missing.

Originally reported in https://github.com/elastic/elasticsearch-js/issues/2148.

**Comment by l-trotta** [comment]
we have it now https://github.com/elastic/elasticsearch-specification/blob/14150f38930fea4c37143dc50f9141f65fd0989b/specification/_types/mapping/specialized.ts#L94
