### ISSUE TITLE
TermsAggregation is missing `shard_min_doc_count` field

### ISSUE THREAD

**Issue by rand0m86** [elastic/elasticsearch-specification#2620]
## 🐛 Missing type
The `shard_min_doc_count` property is missing from the Terms Aggregation API [TermsAggregation](https://github.com/elastic/elasticsearch-specification/blob/33e044d31224bd96da660e99fdb0af668b6404f3/specification/_types/aggregations/bucket.ts#L956-L965).

## Definition
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-shard-min-doc-count

PR for this was created almost a year ago, but since remain unnoticed https://github.com/elastic/elasticsearch-specification/pull/2175.

**Comment by flobernd** [comment]
Closed with #2175
