### ISSUE TITLE
Correctly mapping complex shortcuts

### ISSUE THREAD

**Issue by l-trotta** [elastic/elasticsearch-specification#2713]
Currently, shortcuts only work when the alternative syntax holds a string value, for example [TermQuery](https://github.com/elastic/elasticsearch-specification/blob/90fe7e26253312b8efb4cad3fcb5c49e02bb325d/specification/_types/query_dsl/term.ts#L220).
We found out that there are some requests with more complex shortcuts that allow to "skip" a level of the structure, for example:
- [RankEvalQuery](https://github.com/elastic/elasticsearch-specification/blob/90fe7e26253312b8efb4cad3fcb5c49e02bb325d/specification/_global/rank_eval/types.ts#L111): supports both this extended form: 
  ```
  {
    "metric": {...},
    "requests": [
      {
        "id": "id",
        "request": {
          "query": {
            "match": {...}
         }
        },
        "ratings": [...]
      }
    ]
  }
  ```
  
  and the shortcut version, where `query` is skipped
  
  ```
  {
    "metric": {...},
    "requests": [
      {
        "id": "id",
        "request": {
            "match": {...}
        },
        "ratings": [...]
      }
    ]
  }
  ```
- [FunctionScoreQuery](https://github.com/elastic/elasticsearch-specification/blob/90fe7e26253312b8efb4cad3fcb5c49e02bb325d/specification/_types/query_dsl/compound.ts#L93), where, similarly, `functions` can be skipped:
  ```
  {
    "query": {
	  "function_score": {
	    "functions": [
		  {
		    "gauss": {...}
		  }
	    ]
	  }
    }
  }
  ```
  ```
  {
    "query": {
	  "function_score": {
	    "gauss": {...}
	  }
    }
  }
  ```

Currently the java generator has no way of supporting the deserialization of these complex shortcut, not sure about the other clients.
We can start by adding the correct shortcut annotation to these classes, but we should also make sure that we actually support it.

**Comment by Anaethelion** [comment]
Settings `@shortcut_propery` works for me on `RankEvalQuery` as a shortcut to `Query`.
@flobernd, @JoshMock does adding this works for you ?

**Comment by flobernd** [comment]
The .NET generator currently ignores shortcut properties completely. Feel free to add it here 🙂 I have to come up with a strategy to detect these cases when I work on supporting the shortcuts.

**Comment by JoshMock** [comment]
@Anaethelion I believe this should work for JS as well. :+1:
