### ISSUE TITLE
ILM Phase types are missing properties

### ISSUE THREAD

**Issue by ElenaStoeva** [elastic/elasticsearch-specification#2727]
## 🐛 Missing type

The [ILM Phase types](https://github.com/elastic/elasticsearch-specification/blob/5615a46a870f15fa51edf6a3c4e8c2ed8cc3ebf7/specification/ilm/_types/Phase.ts) are missing some properties:

- The Phase type has incorrect type `configurations`: https://github.com/elastic/elasticsearch-specification/blob/5615a46a870f15fa51edf6a3c4e8c2ed8cc3ebf7/specification/ilm/_types/Phase.ts#L35
- The `Actions` type is incomplete: https://github.com/elastic/elasticsearch-specification/blob/5615a46a870f15fa51edf6a3c4e8c2ed8cc3ebf7/specification/ilm/_types/Phase.ts#L48
- The [shrink configuration type](https://github.com/elastic/elasticsearch-specification/blob/5615a46a870f15fa51edf6a3c4e8c2ed8cc3ebf7/specification/ilm/_types/Phase.ts#L60C14-L60C33) is missing properties `max_primary_shard_size` and `allow_write_after_shrink`
- The [force merge type](https://github.com/elastic/elasticsearch-specification/blob/5615a46a870f15fa51edf6a3c4e8c2ed8cc3ebf7/specification/ilm/_types/Phase.ts#L56) is missing the `index_codec` property
- Missing types for the following actions: [Allocate](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-allocate.html), [Delete](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-delete.html), [Migrate](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-migrate.html), [Read only](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-readonly.html), [Downsample](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-downsample.html), [Searchable snapshot](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-searchable-snapshot.html), [Set priority](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-set-priority.html), [Unfollow](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-unfollow.html), [Wait for snapshot](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-wait-for-snapshot.html)

**Comment by ElenaStoeva** [comment]
Possibly related to https://github.com/elastic/elasticsearch-specification/issues/1533

**Comment by l-trotta** [comment]
Hey, thank you for all the info! Yes `configuration` should be removed from Phase, it was marked as serverless only, but I checked the serverless code and it doesn't even include the Phase class. As for Actions and the configuration, they still have to be mapped correctly, we'll work on it!
