### ISSUE TITLE
Ingest GeoIP database APIs

### ISSUE THREAD

**Issue by yuliacech** [elastic/elasticsearch-specification#2810]
The types for the GeoIP APIs are currently not complete in the specification: 
- Get geoip database configuration API [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/get-geoip-database-api.html)
 The response of the API is not specified, it should be something like 
```ts
{
  databases: {
    id: string;
    version: number;
    modified_date_millis: number;
    database: {
      name: string;
      maxmind: {
        account_id: string;
      };
    };
  }[]
}
```
- Create or update geoip database configuration API [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/put-geoip-database-api.html)
  The specification doesn't have the correct parameters for request body, so it's not possible to pass the `body` object to the js client, should be something like 
```ts
{
    name: string,
    maxmind: {
      account_id: string,
    },
  }
```
- Delete geoip database configuration API [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/delete-geoip-database-api.html)
  The specification doesn't have the correct parameters for the request, should be 
```ts
{
  id: string
}
```

**Comment by pquentin** [comment]
Done in #2815, #2823 and #2824. Backported to 8.15 in #2822, #2828 and #2827.

Thank you, closing!
