### ISSUE TITLE
Calling "simulateIndexTemplate" without a "name" parameter causes client to throw a 500 error

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch-specification#496]
This is blocking https://github.com/elastic/kibana/pull/105863, which I'd like to ship with 7.15.

This is occurring on master in Kibana, which is on `elasticsearch-canary@^8.0.0-canary.13`. To reproduce, call this method with these arguments (you'll need to create a component template called "demo" first):

```
indices.simulateIndexTemplate({
  index_patterns: [ 'foo ],
  composed_of: [ '.deprecation-indexing-mappings', 'demo' ]
});
```

You'll get a 500 error and in the logs you'll see this message:

```
server    log   [20:37:37.561] [error][http] ConfigurationError: Missing required parameter: name
    at IndicesApi.simulateIndexTemplate (/Users/cjcenizal/Documents/GitHub/Elastic/kibana/node_modules/@elastic/elasticsearch/api/api/indices.js:1359:17)
```

According to the [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/simulate-multi-component-templates.html), `name` should be optional. Here are the corresponding [client docs](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_indices_simulateindextemplate) for reference.

**Comment by philkra** [comment]
```
server    log   [20:37:37.561] [error][http] ConfigurationError: Missing required parameter: name
    at IndicesApi.simulateIndexTemplate (/Users/cjcenizal/Documents/GitHub/Elastic/kibana/node_modules/@elastic/elasticsearch/api/api/indices.js:1359:17)
```

Can you attach the Elasticsearch logs? If you're not actively contributing to Kibana, this error message is hard to reason about  a root cause

**Comment by cjcenizal** [comment]
Turns out I was using the `indices.simulateIndexTemplate` API when in reality I wanted to use the `indices.simulateTemplate` API!
