### ISSUE TITLE
Implement Versioned Branching Strategy

### ISSUE THREAD

**Issue by philkra** [elastic/elasticsearch-specification#499]
Currently we are not distinguishing between Elasticsearch's `master` and `7.x` branches. The goal is to follow the same branching strategy.

## Blocking Tasks
- ~~Merge all open [PRs](https://github.com/elastic/elasticsearch-specification/pulls)~~

## New Branches
- [x] Create `7.x` branch from `main`
- [x] Create `7.14` branch from `7.x`

## Tooling & Infra
- [x] Investigate & update the scripts to be version aware - https://github.com/elastic/elasticsearch-specification/pull/503
- [x] Add the backporting bot and ensure only compiler changes are backport-able - https://github.com/elastic/elasticsearch-specification/pull/502
- [x] Read the version number & build hash from the spec artefact and write these values to the [schema.json](https://raw.githubusercontent.com/elastic/elasticsearch-specification/main/output/schema/schema.json) `_info` object - https://github.com/elastic/elasticsearch-specification/pull/501
- [x] [This action](https://github.com/elastic/elasticsearch-specification/blob/f7bb07134d24fe95ba69032c8e3b7d3f99ba5b50/.github/workflows/update-rest-api-json.yml#L28) should be updated as well.

**Comment by delvedor** [comment]
We can merge the other prs later on.
