### ISSUE TITLE
The version can't be automatically updated due to branch protection

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch-specification#528]
Unfortunately, the `update-model-info.yml` action can't be executed successfully because of the branch protections rules we have currently in place.

```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 2 of 2 required status checks are expected. At least 1 approving review is required by reviewers with write access.   
```

Not sure if there is any other way to solve this without passing each time via a PR or by disabling the branch protection. I'll investigate.

Related: #499

**Comment by delvedor** [comment]
Disabled branch protections rules for now. We'll be diligent ;)

**Comment by philkra** [comment]
Is this ticket still relevant?

**Comment by delvedor** [comment]
Nope!
