### ISSUE TITLE
Incorrect TS type for order property in indices.putTemplate request

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch-specification#533]
## 🐛 Wrong type

The `order` property of this request body is expected to be on `body.order` instead of on the root.

## Definition

A request like this completes successfully, despite TS complaints:

```
client.asCurrentUser.indices.putTemplate({
  name: 'test',
  order: 13,
});
```

It looks like `IndicesPutTemplateRequest` expects `order` to be a child of the `body` property: https://github.com/elastic/elasticsearch-specification/blob/main/specification/indices/put_template/IndicesPutTemplateRequest.ts#L49.

```diff
export interface Request extends RequestBase {
  path_parts?: {
    name: Name
  }
  query_parameters?: {
    create?: boolean
    flat_settings?: boolean
    include_type_name?: boolean
    master_timeout?: Time
    timeout?: Time
  }
+  order?: integer
  body?: {
    aliases?: Dictionary<IndexName, Alias>
    index_patterns?: string | string[]
    mappings?: TypeMapping
-    order?: integer
    settings?: Dictionary<string, UserDefinedValue>
    version?: VersionNumber
  }
}
```

**Comment by delvedor** [comment]
According to the [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates-v1.html) it can go either in the body or in the querystring, I'll update our definition to accept it in the quertystring as well :)
