### ISSUE TITLE
estypes has no exported member `SnapshotInfo`

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch-specification#685]
This is defined (https://github.com/elastic/elasticsearch-specification/blob/main/specification/snapshot/_types/SnapshotInfo.ts) but it's not available on `estypes`.

**Comment by delvedor** [comment]
Hello! It's defined, but the exported name is slightly different: [`SnapshotSnapshotInfo`](https://github.com/elastic/elasticsearch-js/blob/b67d42cb5ff7a39a1836d176266ac32af9e72f07/api/types.d.ts#L13690-L13711).
