### ISSUE TITLE
Flat settings for Node Info

### ISSUE THREAD

**Issue by Anaethelion** [elastic/elasticsearch-specification#745]
Currently we support `NodeInfoSettings` for `Nodes.Info` responses.

However, test [free/nodes.info/30_settings.yml](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/nodes.info/30_settings.yml) uses the `flat_settings` parameters which folds everything under settings in dotted properties such as `action.destructive_requires_name`.

Should we:
* duplicate the NodeInfo objects to support both versions
* should we only support the response without `flat_settings`
* find another solution

**Comment by delvedor** [comment]
Fixed in https://github.com/elastic/clients-flight-recorder/pull/787.
