### ISSUE TITLE
[DOCS] Add descriptions to API spec files

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch-specification#964]
Tracking issue for track doc updates to [specification files](https://github.com/elastic/elasticsearch-specification/blob/main/specification/). To prevent duplicated work, leave your name beside a namespace/API you start working on.

It is recommended to prioritize APIs that are listed as "public" instead of "blocked" in the serverless plans: https://docs.google.com/spreadsheets/d/1xFrpFP1dARey8A1QkAoC7JJCGhAZFexMLpRTeY9PAos/

API namespace inventory:
- [x] _global (we should probably subdivide these into distributed- and search-related APIs)
  - [x] bulk https://github.com/elastic/elasticsearch-specification/pull/2269
  - [x] close_point_in_time/open_point_in_time https://github.com/elastic/elasticsearch-specification/pull/2269
  - [x] create https://github.com/elastic/elasticsearch-specification/pull/2270
  - [x] delete https://github.com/elastic/elasticsearch-specification/pull/2270
  - [x] delete_by_query/delete_by_query_rethrottle/update_by_query/update_by_query_rethrottle https://github.com/elastic/elasticsearch-specification/pull/2270
  - [x] delete_script/get_script/put_script/scripts_painless_execute https://github.com/elastic/elasticsearch-specification/pull/2270
  - [x] exists/exists_source https://github.com/elastic/elasticsearch-specification/pull/2271
  - [x] explain https://github.com/elastic/elasticsearch-specification/pull/2271
  - [x] index https://github.com/elastic/elasticsearch-specification/pull/2271
  - [x] msearch_template https://github.com/elastic/elasticsearch-specification/pull/2271
  - [x] mtermvectors/termvectors
  - [x] reindex_rethrottle https://github.com/elastic/elasticsearch-specification/pull/2271
  - [x] render_search_template https://github.com/elastic/elasticsearch-specification/pull/2271
  - [x] search_shards https://github.com/elastic/elasticsearch-specification/pull/2271
  - [x] search_template https://github.com/elastic/elasticsearch-specification/pull/2271
  - [x] search https://github.com/elastic/elasticsearch-specification/pull/2171 
  - [x] queries https://github.com/elastic/elasticsearch-specification/pull/2204 https://github.com/elastic/elasticsearch-specification/pull/2213 https://github.com/elastic/elasticsearch-specification/pull/2217
  - [x] aggs https://github.com/elastic/elasticsearch-specification/pull/2225 https://github.com/elastic/elasticsearch-specification/pull/2237
  - [x] suggesters https://github.com/elastic/elasticsearch-specification/pull/2246
- [x] indices
  - [x] get_settings https://github.com/elastic/elasticsearch-specification/pull/2174
  - [x] put_settings https://github.com/elastic/elasticsearch-specification/pull/2174
  - [x] ... (list to be completed)
- [x] async_search https://github.com/elastic/elasticsearch-specification/pull/2115
- [x] [autoscaling](https://www.elastic.co/guide/en/elasticsearch/reference/master/autoscaling-apis.html) BLOCKED (marked as done)
- [x] [cat](https://www.elastic.co/guide/en/elasticsearch/reference/master/cat.html) https://github.com/elastic/elasticsearch-specification/pull/2124, https://github.com/elastic/elasticsearch-specification/pull/2138, https://github.com/elastic/elasticsearch-specification/pull/2139
- [x] [ccr](https://www.elastic.co/guide/en/elasticsearch/reference/master/ccr-apis.html) BLOCKED (marked as done)
- [x] [cluster](https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster.html) https://github.com/elastic/elasticsearch-specification/pull/2150, https://github.com/elastic/elasticsearch-specification/pull/2154
- [x] component_templates https://github.com/elastic/elasticsearch-specification/pull/2155
- [x] [count](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-count.html) https://github.com/elastic/elasticsearch-specification/pull/2265
- [x] dangling_indices BLOCKED (marked as done)
- [x] [data stream](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-stream-apis.html) https://github.com/elastic/elasticsearch-specification/pull/2163, https://github.com/elastic/elasticsearch-specification/pull/2179
- [x] [enrich](https://www.elastic.co/guide/en/elasticsearch/reference/master/enrich-apis.html) https://github.com/elastic/elasticsearch-specification/pull/2215
- [x] [eql](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-apis.html) https://github.com/elastic/elasticsearch-specification/pull/2216
- [x] [features](https://www.elastic.co/guide/en/elasticsearch/reference/master/features-apis.html) BLOCKED (marked as done)
- [x] fleet INTERNAL (marked as done)
- [x] [graph](https://www.elastic.co/guide/en/elasticsearch/reference/master/graph-explore-api.html) https://github.com/elastic/elasticsearch-specification/pull/2221
- [x] [ilm](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-lifecycle-management-api.html) BLOCKED (marked as done)
- [x] [indices](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices.html) https://github.com/elastic/elasticsearch-specification/pull/2226, https://github.com/elastic/elasticsearch-specification/pull/2230
- [x] [ingest](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest-apis.html) https://github.com/elastic/elasticsearch-specification/pull/2236
- [x] [license](https://www.elastic.co/guide/en/elasticsearch/reference/master/licensing-apis.html) only the `GET license` API is PUBLIC, the rest is BLOCKED (marked as done, GET license is addressed)
- [x] [logstash](https://www.elastic.co/guide/en/elasticsearch/reference/master/logstash-apis.html) https://github.com/elastic/elasticsearch-specification/pull/2240
- [x] [migration](https://www.elastic.co/guide/en/elasticsearch/reference/master/migration-api.html) BLOCKED (marked as done)
- [x] ml https://github.com/elastic/stack-docs/issues/1845; https://github.com/elastic/elasticsearch-specification/pull/2245
- [x] monitoring BLOCKED (marked as done)
- [x] [nodes](https://www.elastic.co/guide/en/elasticsearch/reference/master/node-lifecycle-api.html) https://github.com/elastic/elasticsearch-specification/pull/2248
- [x] reindex https://github.com/elastic/elasticsearch-specification/pull/2247
- [x] [rollup](https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-apis.html) https://github.com/elastic/elasticsearch-specification/pull/2253
- [x] search_application https://github.com/elastic/elasticsearch-specification/pull/2266
- [x] [searchable_snapshots](https://www.elastic.co/guide/en/elasticsearch/reference/master/searchable-snapshots-apis.html) INTERNAL (marked as done)
- [x] [security](https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api.html) https://github.com/elastic/elasticsearch-specification/pull/2152 https://github.com/elastic/elasticsearch-specification/pull/2167 most of the endpoints are addressed, the rest is INTERNAL (marked as done)
- [x] shutdown BLOCKED (marked as done)
- [x] [slm](https://www.elastic.co/guide/en/elasticsearch/reference/master/snapshot-lifecycle-management-api.html) BLOCKED (marked as done)
- [x] [snapshot](https://www.elastic.co/guide/en/elasticsearch/reference/master/snapshot-restore-apis.html) INTERNAL (marked as done)
- [x] [sql](https://www.elastic.co/guide/en/elasticsearch/reference/master/sql-apis.html) https://github.com/elastic/elasticsearch-specification/pull/2264
- [x] ssl INTERNAL (marked as done)
- [x] tasks https://github.com/elastic/elasticsearch-specification/pull/2263
- [x] text_structure
- [x] transform
- [x] [watcher](https://www.elastic.co/guide/en/elasticsearch/reference/master/watcher-api.html) not working on serverless at least for now (marked as done)
- [x] xpack INTERNAL (marked as done)

Other utility files to review:
- [x] _spec_utils
- [x] _types

**Comment by jrodewig** [comment]
Going forward, let's prioritize this work so that we focus on APIs we plan to expose publicly for Serverless. The spreadsheet contains an informal list we can use planning:

https://docs.google.com/spreadsheets/d/1dAt-eZ4zvZVXjTnpCCkMfhCzPXymGGCjOCxeNijbiRc/edit#gid=210925944

**Comment by abdonpijpelink** [comment]
All public APIs have been documented. 🎉 Closing this issue.

We'll follow-up with another issue for the internal and blocked APIs.

**Comment by szabosteve** [comment]
You can find the follow-up issue here: https://github.com/elastic/elasticsearch-specification/issues/2273
